# Generated by Django 3.2.5 on 2021-08-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
